[package]
name = "json"
version = "0.9.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]
description = "JSON implementation in Rust"
repository = "https://github.com/maciejhirsz/json-rust"
documentation = "http://terhix.com/doc/json/"
license = "MIT"

[dependencies]
itoa = "0.1"
ftoa = "0.1"
